# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatroom.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from connectservergui import Ui_ConnectServer

class Ui_ChatRoom(object):
    def open_connect_dialog(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ConnectServer()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, ChatRoom):
        ChatRoom.setObjectName("ChatRoom")
        ChatRoom.setEnabled(True)
        ChatRoom.resize(473, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChatRoom.sizePolicy().hasHeightForWidth())
        ChatRoom.setSizePolicy(sizePolicy)
        ChatRoom.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        ChatRoom.setTabShape(QtWidgets.QTabWidget.Rounded)
        ChatRoom.setDockNestingEnabled(False)
        ChatRoom.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtWidgets.QWidget(ChatRoom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.aliasinput = QtWidgets.QLineEdit(self.centralWidget)
        self.aliasinput.setObjectName("aliasinput")
        self.horizontalLayout_2.addWidget(self.aliasinput)
        self.setalias = QtWidgets.QPushButton(self.centralWidget)
        self.setalias.setObjectName("setalias")
        self.horizontalLayout_2.addWidget(self.setalias)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.messagedisplay = QtWidgets.QTextEdit(self.centralWidget)
        self.messagedisplay.setObjectName("messagedisplay")
        self.verticalLayout_3.addWidget(self.messagedisplay)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.message = QtWidgets.QLineEdit(self.centralWidget)
        self.message.setObjectName("message")
        self.horizontalLayout.addWidget(self.message)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.send = QtWidgets.QPushButton(self.centralWidget)
        self.send.setObjectName("send")
        self.verticalLayout.addWidget(self.send)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.messagedisplay.raise_()
        self.label.raise_()
        self.send.raise_()
        self.label_2.raise_()
        self.setalias.raise_()
        self.aliasinput.raise_()
        self.message.raise_()
        ChatRoom.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ChatRoom)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 473, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        ChatRoom.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(ChatRoom)
        self.mainToolBar.setObjectName("mainToolBar")
        ChatRoom.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(ChatRoom)
        self.statusBar.setObjectName("statusBar")
        ChatRoom.setStatusBar(self.statusBar)
        self.actionConnect = QtWidgets.QAction(ChatRoom)
        self.actionConnect.setObjectName("actionConnect")
        self.actionExit = QtWidgets.QAction(ChatRoom)
        self.actionExit.setObjectName("actionExit")
        # self.menuFile.addSeparator()
        # self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ChatRoom)
        QtCore.QMetaObject.connectSlotsByName(ChatRoom)
        ChatRoom.setTabOrder(self.messagedisplay, self.send)

    def retranslateUi(self, ChatRoom):
        _translate = QtCore.QCoreApplication.translate
        ChatRoom.setWindowTitle(_translate("ChatRoom", "ChatRoom"))
        self.label.setText(_translate("ChatRoom", "Alias:"))
        self.setalias.setText(_translate("ChatRoom", "Set Alias"))
        self.label_2.setText(_translate("ChatRoom", "Message:"))
        self.send.setText(_translate("ChatRoom", "Send"))
        self.menuFile.setTitle(_translate("ChatRoom", "File"))
        self.actionConnect.setText(_translate("ChatRoom", "Connect"))
        self.actionExit.setText(_translate("ChatRoom", "Exit"))
